"""
Tests for ConversationDB repository.
"""
import pytest
from src.database.repository import ConversationDB


class TestConversationDB:
    """Test suite for ConversationDB class."""
    
    def test_init_creates_database(self, conversation_db):
        """Test that database is created on initialization."""
        assert conversation_db.db_path.exists()
    
    def test_save_conversation_metadata(self, conversation_db):
        """Test saving conversation metadata."""
        conv_id, thread_id = conversation_db.save_conversation_metadata("Hello, world!")
        
        assert conv_id is not None
        assert isinstance(conv_id, int)
        # thread_id is auto-generated by trigger, should match pattern
        assert thread_id.startswith("t")
        assert thread_id == f"t{conv_id}"
    
    def test_get_conversation(self, conversation_db):
        """Test retrieving conversation by ID."""
        conv_id, thread_id = conversation_db.save_conversation_metadata("Test message")
        
        result = conversation_db.get_conversation(conv_id)
        
        assert result is not None
        assert result['id'] == conv_id
        assert result['thread_id'] == thread_id
    
    def test_get_conversation_not_found(self, conversation_db):
        """Test retrieving non-existent conversation."""
        result = conversation_db.get_conversation(9999999)
        assert result is None
    
    def test_get_conversations_list(self, conversation_db):
        """Test retrieving list of conversations."""
        # Create multiple conversations
        conv_id1, _ = conversation_db.save_conversation_metadata("First message")
        conv_id2, _ = conversation_db.save_conversation_metadata("Second message")
        conv_id3, _ = conversation_db.save_conversation_metadata("Third message")
        
        conversations = conversation_db.get_conversations_list()
        
        assert len(conversations) == 3
        assert all('id' in conv for conv in conversations)
        assert all('first_message' in conv for conv in conversations)
        assert all('updated_at' in conv for conv in conversations)
        
        # Verify all IDs are present
        ids = [conv['id'] for conv in conversations]
        assert conv_id1 in ids
        assert conv_id2 in ids
        assert conv_id3 in ids
    
    def test_delete_conversation(self, conversation_db):
        """Test deleting a conversation."""
        conv_id, _ = conversation_db.save_conversation_metadata("To be deleted")
        
        result = conversation_db.delete_conversation(conv_id)
        
        assert result is True
        assert conversation_db.get_conversation(conv_id) is None
    
    def test_delete_conversation_not_found(self, conversation_db):
        """Test deleting non-existent conversation."""
        result = conversation_db.delete_conversation(99999)
        assert result is False
    
    def test_thread_id_auto_generated(self, conversation_db):
        """Test that thread_id is automatically generated by trigger."""
        conv_id1, thread_id1 = conversation_db.save_conversation_metadata("Message 1")
        conv_id2, thread_id2 = conversation_db.save_conversation_metadata("Message 2")
        
        assert thread_id1 == f"t{conv_id1}"
        assert thread_id2 == f"t{conv_id2}"
        assert thread_id1 != thread_id2

